stages:
    - update_upm
    - create_release

update_upm_branch:
    stage: update_upm
    image: debian:latest
    before_script:
        - apt-get update
        - apt-get install -y git
    script:
        - echo '### head info'
        - git log -1
        - echo '### create upm branch if not exists'
        - if git show-ref --quiet refs/heads/upm; then git branch -D upm; fi
        - echo '### split upm branch'
        - git subtree split -P "$PKG_ROOT" -b upm
        - echo '### update remote upm branch'
        - git push --force https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git upm
    only:
        - main
    variables:
        PKG_ROOT: "Assets/com.nsaintl.sven"
        CI_SERVER_HOST: "gitlab.lisn.upsaclay.fr"
        CI_PROJECT_PATH: "nsaintl/SVENUnity"

create_release:
    stage: create_release
    image: unityci/editor:latest
    script:
        - echo '### Exporting package to .unitypackage'
        - /opt/unity/Editor/Unity -quit -batchmode -nographics -projectPath . -exportPackage "$PKG_ROOT" "build/SVENUnity.unitypackage"
        - echo '### Creating release'
        - curl --header "PRIVATE-TOKEN: ${GITLAB_PRIVATE_TOKEN}" --data "name=Release $(date +%Y%m%d%H%M%S)&tag_name=$(date +%Y%m%d%H%M%S)&description=Automated release&assets[links][][name]=SVENUnity.unitypackage&assets[links][][url]=${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/build/SVENUnity.unitypackage" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"
    artifacts:
        paths:
            - build/SVENUnity.unitypackage
    only:
        - main
