stages:
    - update_upm

update_upm_branch:
    stage: update_upm
    image: debian:latest
    before_script:
        - apt-get update
        - apt-get install -y git
    script:
        - echo '### head info'
        - git log -1
        - echo '### split upm branch'
        - git subtree split -P "$PKG_ROOT" -b upm
        - echo '### update remote upm branch'
        - echo '### git push https://$CI_JOB_TOKEN@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git upm'
        - git push https://$CI_JOB_TOKEN@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git upm
    only:
        - main
    variables:
        PKG_ROOT: "Assets/com.nsaintl.sven"
