stages:
    - update_upm

update_upm_branch:
    stage: update_upm
    image: debian:latest
    before_script:
        - apt-get update
        - apt-get install -y git
    script:
        - echo '### head info'
        - git log -1
        - echo '### create upm branch if not exists'
        - if git show-ref --quiet refs/heads/upm; then git branch -D upm; fi
        - echo '### split upm branch'
        - git subtree split -P "$PKG_ROOT" -b upm
        - echo '### update remote upm branch'
        - git push --force https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git upm
    only:
        - main
    variables:
        PKG_ROOT: "Assets/com.nsaintl.sven"
        CI_SERVER_HOST: "gitlab.lisn.upsaclay.fr"
        CI_PROJECT_PATH: "nsaintl/SVENUnity"
