stages:
    - update_upm
    - create_release

update_upm_branch:
    stage: update_upm
    image: debian:latest
    before_script:
        - apt-get update
        - apt-get install -y git
    script:
        - echo '### head info'
        - git log -1
        - echo '### create upm branch if not exists'
        - if git show-ref --quiet refs/heads/upm; then git branch -D upm; fi
        - echo '### split upm branch'
        - git subtree split -P "$PKG_ROOT" -b upm
        - echo '### update remote upm branch'
        - git push --force https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git upm
    only:
        - main
    variables:
        PKG_ROOT: "Assets/com.nsaintl.sven"
        CI_SERVER_HOST: "gitlab.lisn.upsaclay.fr"
        CI_PROJECT_PATH: "nsaintl/SVENUnity"

create_unitypackage:
    stage: create_release
    image: unityci/editor:latest
    script:
        - echo '### Exporting Unity package'
        - /opt/unity/Editor/Unity -quit -batchmode -projectPath . -exportPackage "$PKG_ROOT" "SVENUnity.unitypackage"
        - echo '### Creating release'
        - git tag -a "v$(date +%Y%m%d%H%M%S)" -m "Automated release"
        - git push --tags
        - echo '### Uploading Unity package'
        - curl --header "PRIVATE-TOKEN: ${GITLAB_PRIVATE_TOKEN}" --upload-file "SVENUnity.unitypackage" "https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/generic/SVENUnity/$(date +%Y%m%d%H%M%S)/SVENUnity.unitypackage"
    only:
        - main
