PREFIX time: <http://www.w3.org/2006/time#>

SELECT DISTINCT ?graphName ?minInstant ?maxInstant (?maxInstant - ?minInstant AS ?duration)
WHERE {
    SELECT DISTINCT ?graphName (MIN(?instantDateTime) AS ?minInstant)  (MAX(?instantDateTime) AS ?maxInstant)
    WHERE {
        GRAPH ?graphName {
            ?instant a time:Instant ;
                     time:inXSDDateTime ?instantDateTime .
        }
    } GROUP BY ?graphName ORDER BY ?graphName LIMIT 30
} ORDER BY DESC(?minInstant) LIMIT 30